version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: analytics-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: analytics
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: analytics-server
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: analytics
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: analytics-client
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - app-network
    volumes:
      - ./client:/app
      - /app/node_modules

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: 